name: AWS Github Action Github IAM user
run-name: Github Action with IAM user aws-access-key-id
on: [ push ]
jobs:
  deploy:
    name: list s3 buckets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: List s3 buckets
        run: |
          aws s3api list-buckets
          echo "Successful"
          aws cloudformation create-stack \
                    --stack-name root-user-stack \
                    --template-url https://uno-cf.s3.amazonaws.com/CFSimpleDemo.yml